Changes - Modified common/config to use papyros mount options in test mount - Modified common/dmerror, common/dmflakey and common/dmthin to use papyros - Modified common/papyros to use papyros mount options - Modified common/papyros to use default_permissions in _papyros_mount - Modified common/papyros to do sync before unmount - this prevents device busy errors on subsequent mount - Modified common/rc to pass mount options - Modified tests/generic/029 to use kernelcache,0readbuffer - Modified tests/generic/030 to use kernelcache - Modified tests/generic/069 to use kernelcache,writelog - Modified tests/generic/098 to use 0readbuffer - Modified tests/generic/101 to use 0readbuffer - Modified tests/generic/129 to use kernelcache - Modified tests/generic/130 to use 0readbuffer - Modified tests/generic/141 to use kernelcache - Modified tests/generic/322 to use 0readbuffer - Modified tests/generic/325 to use kernelcache - Modified tests/generic/346 to use kernelcache - Modified tests/generic/347 to mkfs papyros with DMTHIN_VOL_DEV in _setup_thin - Modified tests/generic/393 to use 0readbuffer - Modified tests/generic/409 to handle papyros correctly - Modified tests/generic/410 to handle papyros correctly - Modified tests/generic/411 to handle papyros correctly - Modified tests/generic/412 to use 0readbuffer - Modified tests/generic/456 to use kernelcache

diff --git a/common/dmflakey b/common/dmflakey
--- a/common/dmflakey
+++ b/common/dmflakey
@@ -23,7 +23,7 @@ _mount_flakey()
 {
 	if [ "$FSTYP" == "papyros" ]; then
 		_papyros_replace_device $SCRATCH_MD_DIR $SCRATCH_DEV $FLAKEY_DEV
-		_papyros_mount $FLAKEY_DEV $SCRATCH_MNT $SCRATCH_MD_DIR $MOUNT_OPTIONS
+		_papyros_mount $FLAKEY_DEV $SCRATCH_MNT $SCRATCH_MD_DIR $*
 		return $?
 	fi
 
@@ -43,12 +43,21 @@ _unmount_flakey()
 
 _cleanup_flakey()
 {
+	if [ "$FSTYP" == "papyros" ]; then
+		# If dmsetup load fails then we need to make sure to do resume here
+		# otherwise the umount will hang
+		$DMSETUP_PROG resume flakey-test > /dev/null 2>&1
+		_papyros_unmount $SCRATCH_MNT > /dev/null 2>&1
+		_dmsetup_remove flakey-test
+		_papyros_replace_device $SCRATCH_MD_DIR $FLAKEY_DEV $SCRATCH_DEV
+		return $?
+	fi
+
 	# If dmsetup load fails then we need to make sure to do resume here
 	# otherwise the umount will hang
 	$DMSETUP_PROG resume flakey-test > /dev/null 2>&1
 	$UMOUNT_PROG $SCRATCH_MNT > /dev/null 2>&1
 	_dmsetup_remove flakey-test
-	_papyros_replace_device $SCRATCH_MD_DIR $FLAKEY_DEV $SCRATCH_DEV
 }
 
 # _load_flakey_table <table> [lockfs]
@@ -86,10 +95,11 @@ _flakey_drop_and_remount()
 
 	if [ "x$1" = "xyes" ]; then
 		_check_scratch_fs $FLAKEY_DEV
+		shift
 	fi
 
 	_load_flakey_table $FLAKEY_ALLOW_WRITES
-	_mount_flakey
+	_mount_flakey $*
 }
 
 _require_flakey_with_error_writes()
